_BASE_: "../sim10k_prior_art/MIC-Sim10k_NoBurnIn.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
SOLVER:
  BASE_LR: 0.01 # diverges with 0.06
OUTPUT_DIR: "output/sim10k/sim10k_mic_imagenet_2/"
