# this file mimics the settings of using "Mean Teacher" off the shelf with
# the Adaptive Teacher / Unbiased Teacher repo.
# that is:
# - batches are 1/3 weak source, 1/3 strong source, 1/3 target
# - bbox localization losses are disabled
# - random erasing is used as part of the strong augs

_BASE_: "./cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
MODEL:
  WEIGHTS: "models/cityscapes_baseline_foggy_val_model_best_519.pth" 
EMA:
  ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_weak", "labeled_strong", "unlabeled_strong")
  BATCH_RATIOS: (1,1,1)
DOMAIN_ADAPT:
  LOSSES:
    LOC_LOSS_ENABLED: False
  TEACHER:
    ENABLED: True
SOLVER:
  STEPS: (49999,)
  MAX_ITER: 50000
  BACKWARD_AT_END: False
OUTPUT_DIR: "output/cityscapes_meanteacher/"