_BASE_: "./Base-RCNN-FPN-Sim10k.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_strong", )
EMA:
  ENABLED: True
OUTPUT_DIR: "output/sim10k/sim10k_baseline_strongaug_ema/"

SOLVER:
  STEPS: (18000,)
  MAX_ITER: 24000
  CHECKPOINT_PERIOD: 3000