_BASE_: "../cityscapes_startingpoint/DA-RCNN-FPN-Cityscapes_strongaugemastart.yaml"
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
OUTPUT_DIR: "output/cityscapes_sourceweak_onehalftarget/"