_BASE_: "../MeanTeacher-Cityscapes-VGG.yaml"
MODEL:
  META_ARCHITECTURE: "ExtraRCNN"
DATASETS:
  BATCH_CONTENTS: ("labeled_weak", "unlabeled_strong")
  BATCH_RATIOS: (1,1)
AUG:
  LABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_INCLUDE_RANDOM_ERASING: False
  UNLABELED_MIC_AUG: True
DOMAIN_ADAPT:
  LOSSES:
    QUALITY_LOSS_WEIGHT_ENABLED: True
  ALIGN:
    SADA_ENABLED: True
OUTPUT_DIR: "output/cityscapes_mic_vgg/"

# for supercloud issues
TEST:
  EVAL_PERIOD: 100000
SOLVER:
  CHECKPOINT_PERIOD: 1000