_BASE_: "detectron2/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/model_final_f10217.pkl"
  MASK_ON: False
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
SOLVER:
  BASE_LR: 0.06
  STEPS: (1600,)
  MAX_ITER: 2000
  IMS_PER_BATCH: 48
  IMS_PER_GPU: 2
  BACKWARD_AT_END: False
  AMP:
    ENABLED: True
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.01
  CHECKPOINT_PERIOD: 500
VIS_PERIOD: 100
TEST:
  EVAL_PERIOD: 100