_BASE_: "detectron2/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/model_final_f10217.pkl"
  MASK_ON: False
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 2048
  MAX_SIZE_TEST: 2048
SOLVER:
  BASE_LR: 0.02 # LR should be appropriate for IMS_PER_BATCH and MAX_ITERS
  STEPS: (6000, 8000) 
  MAX_ITER: 9000 # Reduced by factor of 10 9000
  IMS_PER_BATCH: 16 # Batch = 16 with 2 per GPU with 8 GPU = 0.02 LR
  IMS_PER_GPU: 8
  BACKWARD_AT_END: False
  AMP:
    ENABLED: True
  WARMUP_ITERS: 10
  WARMUP_FACTOR: 0.01
  CHECKPOINT_PERIOD: 2000 #2000
VIS_PERIOD: 0 
TEST:
  EVAL_PERIOD: 500
LOGGING:
  API_TOKEN: "eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiIyODRhMzEyNi0wOTMxLTQzMWQtYTAwNi05OTY3OGY4YzYyNzQifQ=="
  PROJECT: "ACFRmarine/ALDI-DOAD" 
  ITERS: 100