_BASE_: "../cityscapes_baseline/Base-RCNN-FPN-Cityscapes.yaml"
DOMAIN_ADAPT:
  ALIGN:
    IMG_DA_ENABLED: True
    INS_DA_ENABLED: True
DATASETS:
  UNLABELED: ("cityscapes_foggy_train",)
  BATCH_CONTENTS: ("labeled_weak","unlabeled_weak")
  BATCH_RATIOS: (1,1)
OUTPUT_DIR: "output/cityscapes_align_img_ins/"